# Site settings
title: contact
email: famartwork@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ©2023 FAM, All rights reserved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://famvisualarts.github.io" # "https://famofficially.github.io" #"https://farah-cherif.github.io" # the base hostname & protocol for your site
facebook_username: famvisualarts
twitter_username: famvisualarts
instagram_username: famvisualarts


# Build settings
markdown: kramdown
permalink: pretty
#theme ci dessous mis en commebtaire car erreur de lancer jekyll
#theme: jekyll-theme-cayman