# Site settings
title: contact
email: farah.maamar@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  ©Farah Cherif, PARIS🇫🇷
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
facebook_username: #Artmetry
twitter_username: #artmetry6
instagram_username: #artmetrywork


# Build settings
markdown: kramdown
permalink: pretty
