# Site settings
title: Artmetry
email: artmetryshop@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
facebook_username: Artmetry
twitter_username: artmetry6
github_username:  jekyll3

# Build settings
markdown: kramdown
permalink: pretty
