# Site settings
title: contact
email: famartwork@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ©Fam, Paris🇫🇷
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://famofficially.github.io" #"https://farah-cherif.github.io" # the base hostname & protocol for your site
facebook_username: fam.artwork
twitter_username: fam_officially
instagram_username: fam.officially


# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-cayman